export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'

export const USER_PROPERTY_SUCCESS = "USER_PROPERTY_SUCCESS";

export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const LOGOUT = "LOGOUT";
export const RESET = "RESET";

export const RESET_LOGIN_ERROR = "RESET_LOGIN_ERROR";

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";

export const PROPERTY_LIST_REQUEST = "PROPERTY_LIST_REQUEST";
export const PROPERTY_LIST_SUCCESS = "PROPERTY_LIST_SUCCESS";

export const LOAD_FAVOURITES = "LOAD_FAVOURITES";
export const ADD_FAVOURITES = "ADD_FAVOURITES";


export const LOADING = "LOADING";
export const PAGE_LOADING_REQUEST = "PAGE_LOADING_REQUEST";
export const PAGE_LOADING_SUCCESS = "PAGE_LOADING_SUCCESS";

export const RESET_ERROR = "RESET_ERROR";

export const SHOW_NOTIFY = "SHOW_NOTIFY";
export const HIDE_NOTIFY = "HIDE_NOTIFY";
